name: Test
on:
  push:
  workflow_dispatch:
jobs:
  master:
    strategy:
      matrix:
        path:
          - Programmer-Art-Plus
          - SummerFields
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Apply patch
        run: ./scripts/apply-patch.sh
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@master
        with:
          path: ${{ matrix.path }}
          allow_optifine_mod: true
          artifact_name: ${{ matrix.path }} ${{ github.job }}
  v2_0_2:
    strategy:
      matrix:
        path:
          - Programmer-Art-Plus
          - SummerFields
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Apply patch
        run: ./scripts/apply-patch.sh
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v2.0.2
        with:
          path: ${{ matrix.path }}
          allow_optifine_mod: true
          artifact_name: ${{ matrix.path }} ${{ github.job }}
  v2_0_1:
    strategy:
      matrix:
        path:
          - Programmer-Art-Plus
          - SummerFields
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Apply patch
        run: ./scripts/apply-patch.sh
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v2.0.1
        with:
          path: ${{ matrix.path }}
          allow_optifine_mod: true
          artifact_name: ${{ matrix.path }} ${{ github.job }}
  v3:
    strategy:
      matrix:
        path:
          - Programmer-Art-Plus
          - SummerFields
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Apply patch
        run: ./scripts/apply-patch.sh
      - name: Run PackSquash
        uses: sya-ri/PackSquash-action@v3
        with:
          path: ${{ matrix.path }}
          allow_optifine_mod: true
          artifact_name: ${{ matrix.path }} ${{ github.job }}