name: Test
on:
  workflow_dispatch:
    inputs:
      path:
        description: Enter a path of the resource pack for a test. (Programmer-Art-Plus, SummerFields)
        required: true
jobs:
  master:
    if: github.event.inputs.path == 'Programmer-Art-Plus' ||github.event.inputs.path == 'SummerFields'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Apply patch
        run: ./scripts/apply-patch.sh
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@master
        with:
          path: ${{ github.event.inputs.path }}
          allow_optifine_mod: true
          artifact_name: ${{ github.event.inputs.path }} ${{ github.job }}
  v2_0_2:
    if: github.event.inputs.path == 'Programmer-Art-Plus' ||github.event.inputs.path == 'SummerFields'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Apply patch
        run: ./scripts/apply-patch.sh
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v2.0.2
        with:
          path: ${{ github.event.inputs.path }}
          allow_optifine_mod: true
          artifact_name: ${{ github.event.inputs.path }} ${{ github.job }}
  v2_0_1:
    if: github.event.inputs.path == 'Programmer-Art-Plus' ||github.event.inputs.path == 'SummerFields'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Apply patch
        run: ./scripts/apply-patch.sh
      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v2.0.1
        with:
          path: ${{ github.event.inputs.path }}
          allow_optifine_mod: true
          artifact_name: ${{ github.event.inputs.path }} ${{ github.job }}
  v3:
    if: github.event.inputs.path == 'Programmer-Art-Plus' ||github.event.inputs.path == 'SummerFields'
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Apply patch
        run: ./scripts/apply-patch.sh
      - name: Run PackSquash
        uses: sya-ri/PackSquash-action@v3
        with:
          path: ${{ github.event.inputs.path }}
          allow_optifine_mod: true
          artifact_name: ${{ github.event.inputs.path }} ${{ github.job }}